var dir_1a6ae12f0dbe11c3b8002c71effb1701 =
[
    [ "AgregarEtiquetaClienteUsuario.cs", "_agregar_etiqueta_cliente_usuario_8cs.html", "_agregar_etiqueta_cliente_usuario_8cs" ],
    [ "AsignarClienteVendedor.cs", "_asignar_cliente_vendedor_8cs.html", "_asignar_cliente_vendedor_8cs" ],
    [ "BuscarClienteUsuario.cs", "_buscar_cliente_usuario_8cs.html", "_buscar_cliente_usuario_8cs" ],
    [ "ContactoPendienteClienteUsuario.cs", "_contacto_pendiente_cliente_usuario_8cs.html", "_contacto_pendiente_cliente_usuario_8cs" ],
    [ "CrearClienteUsuario.cs", "_crear_cliente_usuario_8cs.html", "_crear_cliente_usuario_8cs" ],
    [ "CrearEtiquetaUsuario.cs", "_crear_etiqueta_usuario_8cs.html", "_crear_etiqueta_usuario_8cs" ],
    [ "CrearUsuarioAdmin.cs", "_crear_usuario_admin_8cs.html", "_crear_usuario_admin_8cs" ],
    [ "CrearVendedorUsuario.cs", "_crear_vendedor_usuario_8cs.html", "_crear_vendedor_usuario_8cs" ],
    [ "EliminarClienteUsuario.cs", "_eliminar_cliente_usuario_8cs.html", "_eliminar_cliente_usuario_8cs" ],
    [ "EliminarUsuarioAdmin.cs", "_eliminar_usuario_admin_8cs.html", "_eliminar_usuario_admin_8cs" ],
    [ "InteraccionesClienteUsuario.cs", "_interacciones_cliente_usuario_8cs.html", "_interacciones_cliente_usuario_8cs" ],
    [ "ListarClientesUsuario.cs", "_listar_clientes_usuario_8cs.html", "_listar_clientes_usuario_8cs" ],
    [ "ListarClientesVendedor.cs", "_listar_clientes_vendedor_8cs.html", "_listar_clientes_vendedor_8cs" ],
    [ "ListarVendedoresVendedorUsuario.cs", "_listar_vendedores_vendedor_usuario_8cs.html", "_listar_vendedores_vendedor_usuario_8cs" ],
    [ "Login.cs", "_login_8cs.html", "_login_8cs" ],
    [ "Logout.cs", "_logout_8cs.html", "_logout_8cs" ],
    [ "ModificarClienteUsuario.cs", "_modificar_cliente_usuario_8cs.html", "_modificar_cliente_usuario_8cs" ],
    [ "PromedioVentasUsuario.cs", "_promedio_ventas_usuario_8cs.html", "_promedio_ventas_usuario_8cs" ],
    [ "RegistrarCotizacionClienteUsuario.cs", "_registrar_cotizacion_cliente_usuario_8cs.html", "_registrar_cotizacion_cliente_usuario_8cs" ],
    [ "RegistrarVentaClienteUsuario.cs", "_registrar_venta_cliente_usuario_8cs.html", "_registrar_venta_cliente_usuario_8cs" ],
    [ "RegistroComunicacionUsuario.cs", "_registro_comunicacion_usuario_8cs.html", "_registro_comunicacion_usuario_8cs" ],
    [ "SuspenderUsuarioAdmin.cs", "_suspender_usuario_admin_8cs.html", "_suspender_usuario_admin_8cs" ],
    [ "UltimaInteraccionClienteUsuario.cs", "_ultima_interaccion_cliente_usuario_8cs.html", "_ultima_interaccion_cliente_usuario_8cs" ],
    [ "VerPanelResumenUsuario.cs", "_ver_panel_resumen_usuario_8cs.html", "_ver_panel_resumen_usuario_8cs" ]
];