var hierarchy =
[
    [ "Library.Clases_principales.Administrador", "class_library_1_1_clases__principales_1_1_administrador.html", null ],
    [ "Library.Tests.AdministradorTest", "class_library_1_1_tests_1_1_administrador_test.html", null ],
    [ "Library.BotCore.BotCore", "class_library_1_1_bot_core_1_1_bot_core.html", null ],
    [ "Library.Tests.BotCoreTest", "class_library_1_1_tests_1_1_bot_core_test.html", null ],
    [ "BotDiscordBridge", "class_bot_discord_bridge.html", null ],
    [ "Library.Clases_principales.Cliente", "class_library_1_1_clases__principales_1_1_cliente.html", null ],
    [ "Library.Tests.ComandosBotTest", "class_library_1_1_tests_1_1_comandos_bot_test.html", null ],
    [ "Library.Clases_tipos.Email", "class_library_1_1_clases__tipos_1_1_email.html", null ],
    [ "Library.Clases_tipos.Emails", "class_library_1_1_clases__tipos_1_1_emails.html", null ],
    [ "Library.Fachadas.Fachada", "class_library_1_1_fachadas_1_1_fachada.html", null ],
    [ "Library.Fachadas.FachadaRegistro", "class_library_1_1_fachadas_1_1_fachada_registro.html", null ],
    [ "Library.Tests.FachadaRegistroTest", "class_library_1_1_tests_1_1_fachada_registro_test.html", null ],
    [ "Library.BotCore.Interfaces.IBotCommand", "interface_library_1_1_bot_core_1_1_interfaces_1_1_i_bot_command.html", [
      [ "Library.BotCore.Comandos.AgregarEtiquetaClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_agregar_etiqueta_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.AsignarClienteVendedor", "class_library_1_1_bot_core_1_1_comandos_1_1_asignar_cliente_vendedor.html", null ],
      [ "Library.BotCore.Comandos.BuscarClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_buscar_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.ContactoPendienteClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_contacto_pendiente_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.CrearClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.CrearEtiquetaUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_etiqueta_usuario.html", null ],
      [ "Library.BotCore.Comandos.CrearUsuarioAdmin", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_usuario_admin.html", null ],
      [ "Library.BotCore.Comandos.CrearVendedorUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_vendedor_usuario.html", null ],
      [ "Library.BotCore.Comandos.EliminarClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_eliminar_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.EliminarUsuarioAdmin", "class_library_1_1_bot_core_1_1_comandos_1_1_eliminar_usuario_admin.html", null ],
      [ "Library.BotCore.Comandos.InteraccionesClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_interacciones_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.ListarClientesCommand", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_clientes_command.html", null ],
      [ "Library.BotCore.Comandos.ListarClientesVendedor", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_clientes_vendedor.html", null ],
      [ "Library.BotCore.Comandos.ListarVendedoresVendedorUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_vendedores_vendedor_usuario.html", null ],
      [ "Library.BotCore.Comandos.LoginCommand", "class_library_1_1_bot_core_1_1_comandos_1_1_login_command.html", null ],
      [ "Library.BotCore.Comandos.LogoutCommand", "class_library_1_1_bot_core_1_1_comandos_1_1_logout_command.html", null ],
      [ "Library.BotCore.Comandos.ModificarClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_modificar_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.PromedioVentasUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_promedio_ventas_usuario.html", null ],
      [ "Library.BotCore.Comandos.RegistrarCotizacionClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_registrar_cotizacion_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.RegistrarVentaClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_registrar_venta_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.RegistroComunicacionUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_registro_comunicacion_usuario.html", null ],
      [ "Library.BotCore.Comandos.SuspenderUsuarioAdmin", "class_library_1_1_bot_core_1_1_comandos_1_1_suspender_usuario_admin.html", null ],
      [ "Library.BotCore.Comandos.UltimaInteraccionClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_ultima_interaccion_cliente_usuario.html", null ],
      [ "Library.BotCore.Comandos.VerPanelResumenUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_ver_panel_resumen_usuario.html", null ]
    ] ],
    [ "Library.BotCore.Interfaces.IMessageContext", "interface_library_1_1_bot_core_1_1_interfaces_1_1_i_message_context.html", [
      [ "Library.BotCore.MensajeDeConsola", "class_library_1_1_bot_core_1_1_mensaje_de_consola.html", null ],
      [ "Library.PuenteDiscord.DiscordMessageContext", "class_library_1_1_puente_discord_1_1_discord_message_context.html", null ]
    ] ],
    [ "Library.Clases_tipos.Llamada", "class_library_1_1_clases__tipos_1_1_llamada.html", null ],
    [ "Library.Clases_tipos.Llamadas", "class_library_1_1_clases__tipos_1_1_llamadas.html", null ],
    [ "Library.Clases_tipos.Mensaje", "class_library_1_1_clases__tipos_1_1_mensaje.html", null ],
    [ "Library.Clases_tipos.Mensajes", "class_library_1_1_clases__tipos_1_1_mensajes.html", null ],
    [ "Library.Clases_principales.PanelResumen", "class_library_1_1_clases__principales_1_1_panel_resumen.html", null ],
    [ "Library.Clases_tipos.Precio", "class_library_1_1_clases__tipos_1_1_precio.html", null ],
    [ "Program", "class_program.html", null ],
    [ "Library.Clases_principales.RegistroCliente", "class_library_1_1_clases__principales_1_1_registro_cliente.html", null ],
    [ "Library.Tests.RegistroClientesTests", "class_library_1_1_tests_1_1_registro_clientes_tests.html", null ],
    [ "Library.Clases_tipos.Reunion", "class_library_1_1_clases__tipos_1_1_reunion.html", null ],
    [ "Library.BotCore.Sesion", "class_library_1_1_bot_core_1_1_sesion.html", null ],
    [ "Library.Fachadas.Singleton&lt; T &gt;", "class_library_1_1_fachadas_1_1_singleton-1-g.html", null ],
    [ "Library.Tests.Tests", "class_library_1_1_tests_1_1_tests.html", null ],
    [ "Library.Clases_principales.Usuario", "class_library_1_1_clases__principales_1_1_usuario.html", null ],
    [ "Library.Tests.UsuarioTests", "class_library_1_1_tests_1_1_usuario_tests.html", null ],
    [ "Library.Clases_principales.Vendedor", "class_library_1_1_clases__principales_1_1_vendedor.html", null ],
    [ "Library.Tests.VendedorTests", "class_library_1_1_tests_1_1_vendedor_tests.html", null ],
    [ "Library.Clases_tipos.Venta", "class_library_1_1_clases__tipos_1_1_venta.html", null ],
    [ "Library.Clases_tipos.Ventas", "class_library_1_1_clases__tipos_1_1_ventas.html", null ]
];