var namespace_library_1_1_bot_core_1_1_comandos =
[
    [ "AgregarEtiquetaClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_agregar_etiqueta_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_agregar_etiqueta_cliente_usuario" ],
    [ "AsignarClienteVendedor", "class_library_1_1_bot_core_1_1_comandos_1_1_asignar_cliente_vendedor.html", "class_library_1_1_bot_core_1_1_comandos_1_1_asignar_cliente_vendedor" ],
    [ "BuscarClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_buscar_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_buscar_cliente_usuario" ],
    [ "ContactoPendienteClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_contacto_pendiente_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_contacto_pendiente_cliente_usuario" ],
    [ "CrearClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_cliente_usuario" ],
    [ "CrearEtiquetaUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_etiqueta_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_etiqueta_usuario" ],
    [ "CrearUsuarioAdmin", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_usuario_admin.html", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_usuario_admin" ],
    [ "CrearVendedorUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_vendedor_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_crear_vendedor_usuario" ],
    [ "EliminarClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_eliminar_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_eliminar_cliente_usuario" ],
    [ "EliminarUsuarioAdmin", "class_library_1_1_bot_core_1_1_comandos_1_1_eliminar_usuario_admin.html", "class_library_1_1_bot_core_1_1_comandos_1_1_eliminar_usuario_admin" ],
    [ "InteraccionesClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_interacciones_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_interacciones_cliente_usuario" ],
    [ "ListarClientesCommand", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_clientes_command.html", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_clientes_command" ],
    [ "ListarClientesVendedor", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_clientes_vendedor.html", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_clientes_vendedor" ],
    [ "ListarVendedoresVendedorUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_vendedores_vendedor_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_listar_vendedores_vendedor_usuario" ],
    [ "LoginCommand", "class_library_1_1_bot_core_1_1_comandos_1_1_login_command.html", "class_library_1_1_bot_core_1_1_comandos_1_1_login_command" ],
    [ "LogoutCommand", "class_library_1_1_bot_core_1_1_comandos_1_1_logout_command.html", "class_library_1_1_bot_core_1_1_comandos_1_1_logout_command" ],
    [ "ModificarClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_modificar_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_modificar_cliente_usuario" ],
    [ "PromedioVentasUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_promedio_ventas_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_promedio_ventas_usuario" ],
    [ "RegistrarCotizacionClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_registrar_cotizacion_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_registrar_cotizacion_cliente_usuario" ],
    [ "RegistrarVentaClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_registrar_venta_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_registrar_venta_cliente_usuario" ],
    [ "RegistroComunicacionUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_registro_comunicacion_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_registro_comunicacion_usuario" ],
    [ "SuspenderUsuarioAdmin", "class_library_1_1_bot_core_1_1_comandos_1_1_suspender_usuario_admin.html", "class_library_1_1_bot_core_1_1_comandos_1_1_suspender_usuario_admin" ],
    [ "UltimaInteraccionClienteUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_ultima_interaccion_cliente_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_ultima_interaccion_cliente_usuario" ],
    [ "VerPanelResumenUsuario", "class_library_1_1_bot_core_1_1_comandos_1_1_ver_panel_resumen_usuario.html", "class_library_1_1_bot_core_1_1_comandos_1_1_ver_panel_resumen_usuario" ]
];